require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
source 'https://cdn.cocoapods.org'
require_relative '../node_modules/react-native/scripts/react_native_pods'

ENV['RCT_NEW_ARCH_ENABLED'] = '0'

# From RNP docs here: https://www.npmjs.com/package/react-native-permissions/v/4.0.1
def node_require(script)
  # Resolve script with node to allow for hoisting
  require `node -p "require.resolve('#{script}', {paths: [process.argv[1]]})" #{__dir__}`.strip
end
  
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '15.5'
prepare_react_native_project!

# uncomment wanted permissions (also from RNP docs linked above)
setup_permissions([
  # 'AppTrackingTransparency',
  # 'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
  'Camera',
  # 'Contacts',
  'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
  # 'MediaLibrary',
  # 'Microphone',
  # 'Motion',
  # 'Notifications'
  # 'PhotoLibrary',
  # 'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])

# Flipper was removed in React Native 0.77+

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AriesBifold' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  #permissions_path = '../node_modules/react-native-permissions/ios'
  #pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  #pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  # use reactNativePermissionsIOS.json for permissions instead!!!


  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    #:flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'AriesBifoldTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Set deployment target and Swift search paths
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
        
        # Ensure Swift search paths are present in all pods
        config.build_settings['LIBRARY_SEARCH_PATHS'] ||= ['$(inherited)']
        config.build_settings['LIBRARY_SEARCH_PATHS'] << '$(SDKROOT)/usr/lib/swift'
        config.build_settings['LIBRARY_SEARCH_PATHS'] << '$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)'
        
        # Don't embed swift standard libraries in static libraries or bundles
        # The main app target (AriesBifold) should have it set to YES
        if target.name == 'AriesBifold' || target.name.include?('Pods-AriesBifold')
          config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
        elsif target.respond_to?(:product_type) && target.product_type == 'com.apple.product-type.bundle'
          config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        else
          # Default to NO for pods to avoid "Build input file cannot be found" errors in bundles
          config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
      end
    end

    # Fix RNArgon2 Swift compilation issues with CatCrypto module dependencies
    installer.pods_project.targets.each do |target|
      if target.name == 'RNArgon2'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5.0'
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
          config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
          config.build_settings['ENABLE_MODULE_VERIFIER'] = 'NO'
          config.build_settings['DEFINES_MODULE'] = 'YES'

          # Add CatCrypto's submodule paths for Argon2, MD6, SHA3
          catcrypto_modulemap_dir = "#{installer.sandbox.pod_dir('CatCrypto')}/Sources/ModuleMaps"
          swift_include_paths = [
            "#{catcrypto_modulemap_dir}/Argon2",
            "#{catcrypto_modulemap_dir}/MD6",
            "#{catcrypto_modulemap_dir}/SHA3"
          ]

          # Add to Swift search paths
          config.build_settings['SWIFT_INCLUDE_PATHS'] ||= ['$(inherited)']
          config.build_settings['SWIFT_INCLUDE_PATHS'] += swift_include_paths

          # Also add to OTHER_SWIFT_FLAGS for explicit module imports
          config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)']
          swift_include_paths.each do |path|
            config.build_settings['OTHER_SWIFT_FLAGS'] << "-Xcc"
            config.build_settings['OTHER_SWIFT_FLAGS'] << "-I#{path}"
          end
        end
      end
    end
  end
end